name: Create Tag on PR Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verify with Maven
      run: mvn -B verify -Pproduction

    - name: Fetch latest tag
      id: fetch_latest_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Increment tag version
      id: increment_tag
      run: |
        latest_tag=${{ env.latest_tag }}
        IFS='.' read -r -a tag_parts <<< "$latest_tag"
        new_tag="${tag_parts[0]}.${tag_parts[1]}.$((tag_parts[2] + 1))"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create new tag
      if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag ${{ env.new_tag }}
        git push origin ${{ env.new_tag }}
