name: Maven Build and Run Tests 

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
#      env:
#         VAADIN_OFFLINE_KEY: ${{ secrets.VAADIN_PRODMODE_CI_SERVER_KEY }}
      run: mvn -B clean package -Pproduction --file pom.xml

    - name: Build test container
      run: docker build . -t ccapp:latest-test 

    # Run the continaer
    - name: Run test container
      run: docker run -d --name ccapp-test -p 8080:8080 ccapp:latest-test

    # TODO, one day make a proper test for this... 
    - name: Wait for app to be ready (max 20s) and test with curl
      run: |
        for i in {1..20}; do
          if curl -f http://localhost:8080/; then
          exit 0
          fi
          sleep 1
        done
        echo "App did not become ready in 20 seconds"
        exit 1

    # Print docker logs
    - name: Print container logs
      run: docker logs ccapp-test

    - name: Stop and remove container
      run: |
        docker stop ccapp-test
        docker rm ccapp-test

    # If fail, print docker logs
    - name: Print docker logs if build fails
      if: failure()
      run: docker logs ccapp-test || true

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive